In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
'/content/drive/mydrive/COLAB NOTEBOOKS'

'/content/drive/mydrive/COLAB NOTEBOOKS'

In [ ]:
import pandas as pd
pd.read_csv("/content/drive/MyDrive/Air Quality Missing Data.csv")

           Date  Ozone  Solar  Wind  Temp
0    01-05-1976   41.0  190.0   7.4    67
1    02-05-1976   36.0  118.0   8.0    72
2    03-05-1976   12.0  149.0  12.6    74
3    04-05-1976   18.0  313.0  11.5    62
4    05-05-1976    NaN    NaN  14.3    56
..          ...    ...    ...   ...   ...
148  26-09-1976   30.0  193.0   6.9    70
149  27-09-1976    NaN  145.0  13.2    77
150  28-09-1976   14.0  191.0  14.3    75
151  29-09-1976   18.0  131.0   8.0    76
152  30-09-1976   20.0  223.0  11.5    68

[153 rows x 5 columns]

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Air Quality Missing Data.csv")
df

           Date  Ozone  Solar  Wind  Temp
0    01-05-1976   41.0  190.0   7.4    67
1    02-05-1976   36.0  118.0   8.0    72
2    03-05-1976   12.0  149.0  12.6    74
3    04-05-1976   18.0  313.0  11.5    62
4    05-05-1976    NaN    NaN  14.3    56
..          ...    ...    ...   ...   ...
148  26-09-1976   30.0  193.0   6.9    70
149  27-09-1976    NaN  145.0  13.2    77
150  28-09-1976   14.0  191.0  14.3    75
151  29-09-1976   18.0  131.0   8.0    76
152  30-09-1976   20.0  223.0  11.5    68

[153 rows x 5 columns]

In [ ]:
print(df.isnull().sum())

Date      0
Ozone    37
Solar     7
Wind      0
Temp      0
dtype: int64

In [ ]:
df = df.convert_dtypes()
df

           Date  Ozone  Solar  Wind  Temp
0    01-05-1976     41    190   7.4    67
1    02-05-1976     36    118   8.0    72
2    03-05-1976     12    149  12.6    74
3    04-05-1976     18    313  11.5    62
4    05-05-1976   <NA>   <NA>  14.3    56
..          ...    ...    ...   ...   ...
148  26-09-1976     30    193   6.9    70
149  27-09-1976   <NA>    145  13.2    77
150  28-09-1976     14    191  14.3    75
151  29-09-1976     18    131   8.0    76
152  30-09-1976     20    223  11.5    68

[153 rows x 5 columns]

In [ ]:
df.drop_duplicates(inplace=True)
df

           Date  Ozone  Solar  Wind  Temp
0    01-05-1976     41    190   7.4    67
1    02-05-1976     36    118   8.0    72
2    03-05-1976     12    149  12.6    74
3    04-05-1976     18    313  11.5    62
4    05-05-1976   <NA>   <NA>  14.3    56
..          ...    ...    ...   ...   ...
148  26-09-1976     30    193   6.9    70
149  27-09-1976   <NA>    145  13.2    77
150  28-09-1976     14    191  14.3    75
151  29-09-1976     18    131   8.0    76
152  30-09-1976     20    223  11.5    68

[153 rows x 5 columns]

In [ ]:
df.to_csv("Cleaned_Air_Quality.csv", index=False)
df

           Date  Ozone  Solar  Wind  Temp
0    01-05-1976     41    190   7.4    67
1    02-05-1976     36    118   8.0    72
2    03-05-1976     12    149  12.6    74
3    04-05-1976     18    313  11.5    62
4    05-05-1976   <NA>   <NA>  14.3    56
..          ...    ...    ...   ...   ...
148  26-09-1976     30    193   6.9    70
149  27-09-1976   <NA>    145  13.2    77
150  28-09-1976     14    191  14.3    75
151  29-09-1976     18    131   8.0    76
152  30-09-1976     20    223  11.5    68

[153 rows x 5 columns]

In [ ]:
df.head()
df.info()
df.describe()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    153 non-null    string
 1   Ozone   153 non-null    Int64
 2   Solar   153 non-null    Int64
 3   Wind    153 non-null    Float64
 4   Temp    153 non-null    Int64
dtypes: Float64(1), Int64(3), string(1)
memory usage: 6.7 KB

           Date  Ozone  Solar  Wind  Temp
0    01-05-1976     41    190   7.4    67
1    02-05-1976     36    118   8.0    72
2    03-05-1976     12    149  12.6    74
3    04-05-1976     18    313  11.5    62
4    05-05-1976     23    238  14.3    56
..          ...    ...    ...   ...   ...
148  26-09-1976     30    193   6.9    70
149  27-09-1976     23    145  13.2    77
150  28-09-1976     14    191  14.3    75
151  29-09-1976     18    131   8.0    76
152  30-09-1976     20    223  11.5    68

[153 rows x 5 columns]