In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
'/content/drive/mydrive/COLAB NOTEBOOKS'

'/content/drive/mydrive/COLAB NOTEBOOKS'

In [ ]:
import pandas as pd
pd.read_csv("/content/drive/MyDrive/Air Quality Missing Data.csv")

           Date  Ozone  Solar  Wind  Temp
0    01-05-1976   41.0  190.0   7.4    67
1    02-05-1976   36.0  118.0   8.0    72
2    03-05-1976   12.0  149.0  12.6    74
3    04-05-1976   18.0  313.0  11.5    62
4    05-05-1976    NaN    NaN  14.3    56
..          ...    ...    ...   ...   ...
148  26-09-1976   30.0  193.0   6.9    70
149  27-09-1976    NaN  145.0  13.2    77
150  28-09-1976   14.0  191.0  14.3    75
151  29-09-1976   18.0  131.0   8.0    76
152  30-09-1976   20.0  223.0  11.5    68

[153 rows x 5 columns]

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Air Quality Missing Data.csv")
df

           Date  Ozone  Solar  Wind  Temp
0    01-05-1976   41.0  190.0   7.4    67
1    02-05-1976   36.0  118.0   8.0    72
2    03-05-1976   12.0  149.0  12.6    74
3    04-05-1976   18.0  313.0  11.5    62
4    05-05-1976    NaN    NaN  14.3    56
..          ...    ...    ...   ...   ...
148  26-09-1976   30.0  193.0   6.9    70
149  27-09-1976    NaN  145.0  13.2    77
150  28-09-1976   14.0  191.0  14.3    75
151  29-09-1976   18.0  131.0   8.0    76
152  30-09-1976   20.0  223.0  11.5    68

[153 rows x 5 columns]

In [ ]:
df.head(15)

          Date  Ozone  Solar  Wind  Temp
0   01-05-1976   41.0  190.0   7.4    67
1   02-05-1976   36.0  118.0   8.0    72
2   03-05-1976   12.0  149.0  12.6    74
3   04-05-1976   18.0  313.0  11.5    62
4   05-05-1976    NaN    NaN  14.3    56
5   06-05-1976   28.0    NaN  14.9    66
6   07-05-1976   23.0  299.0   8.6    65
7   08-05-1976   19.0   99.0  13.8    59
8   09-05-1976    8.0   19.0  20.1    61
9   10-05-1976    NaN  194.0   8.6    69
10  11-05-1976    7.0    NaN   6.9    74
11  12-05-1976   16.0  256.0   9.7    69
12  13-05-1976   11.0  290.0   9.2    66
13  14-05-1976   14.0  274.0  10.9    68
14  15-05-1976   18.0   65.0  13.2    58

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    153 non-null    object
 1   Ozone   116 non-null    float64
 2   Solar   146 non-null    float64
 3   Wind    153 non-null    float64
 4   Temp    153 non-null    int64
dtypes: float64(3), int64(1), object(1)
memory usage: 6.1+ KB

In [ ]:
df.isnull()

      Date  Ozone  Solar   Wind   Temp
0    False  False  False  False  False
1    False  False  False  False  False
2    False  False  False  False  False
3    False  False  False  False  False
4    False   True   True  False  False
..     ...    ...    ...    ...    ...
148  False  False  False  False  False
149  False   True  False  False  False
150  False  False  False  False  False
151  False  False  False  False  False
152  False  False  False  False  False

[153 rows x 5 columns]

In [ ]:
df.fillna("filled")

           Date   Ozone   Solar  Wind  Temp
0    01-05-1976    41.0   190.0   7.4    67
1    02-05-1976    36.0   118.0   8.0    72
2    03-05-1976    12.0   149.0  12.6    74
3    04-05-1976    18.0   313.0  11.5    62
4    05-05-1976  filled  filled  14.3    56
..          ...     ...     ...   ...   ...
148  26-09-1976    30.0   193.0   6.9    70
149  27-09-1976  filled   145.0  13.2    77
150  28-09-1976    14.0   191.0  14.3    75
151  29-09-1976    18.0   131.0   8.0    76
152  30-09-1976    20.0   223.0  11.5    68

[153 rows x 5 columns]

In [ ]:
df.dropna()

           Date  Ozone  Solar  Wind  Temp
0    01-05-1976   41.0  190.0   7.4    67
1    02-05-1976   36.0  118.0   8.0    72
2    03-05-1976   12.0  149.0  12.6    74
3    04-05-1976   18.0  313.0  11.5    62
6    07-05-1976   23.0  299.0   8.6    65
..          ...    ...    ...   ...   ...
147  25-09-1976   14.0   20.0  16.6    63
148  26-09-1976   30.0  193.0   6.9    70
150  28-09-1976   14.0  191.0  14.3    75
151  29-09-1976   18.0  131.0   8.0    76
152  30-09-1976   20.0  223.0  11.5    68

[111 rows x 5 columns]

In [ ]:
df["Solar"].fillna(df["Solar"].mean)

0                                                  190.0
1                                                  118.0
2                                                  149.0
3                                                  313.0
4      <bound method Series.mean of 0      190.0\n1  ...
                             ...
148                                                193.0
149                                                145.0
150                                                191.0
151                                                131.0
152                                                223.0
Name: Solar, Length: 153, dtype: object

In [ ]:
df.tail(17)

           Date  Ozone  Solar  Wind  Temp
136  14-09-1976    9.0   24.0  10.9    71
137  15-09-1976   13.0  112.0  11.5    71
138  16-09-1976   46.0  237.0   6.9    78
139  17-09-1976   18.0  224.0  13.8    67
140  18-09-1976   13.0   27.0  10.3    76
141  19-09-1976   24.0  238.0  10.3    68
142  20-09-1976   16.0  201.0   8.0    82
143  21-09-1976   13.0  238.0  12.6    64
144  22-09-1976   23.0   14.0   9.2    71
145  23-09-1976   36.0  139.0  10.3    81
146  24-09-1976    7.0   49.0  10.3    69
147  25-09-1976   14.0   20.0  16.6    63
148  26-09-1976   30.0  193.0   6.9    70
149  27-09-1976    NaN  145.0  13.2    77
150  28-09-1976   14.0  191.0  14.3    75
151  29-09-1976   18.0  131.0   8.0    76
152  30-09-1976   20.0  223.0  11.5    68

In [ ]:
df.rename(columns={'PM2.5':'PM25'}, inplace=True)
df

           Date  Ozone  Solar  Wind  Temp
0    01-05-1976   41.0  190.0   7.4    67
1    02-05-1976   36.0  118.0   8.0    72
2    03-05-1976   12.0  149.0  12.6    74
3    04-05-1976   18.0  313.0  11.5    62
4    05-05-1976    NaN    NaN  14.3    56
..          ...    ...    ...   ...   ...
148  26-09-1976   30.0  193.0   6.9    70
149  27-09-1976    NaN  145.0  13.2    77
150  28-09-1976   14.0  191.0  14.3    75
151  29-09-1976   18.0  131.0   8.0    76
152  30-09-1976   20.0  223.0  11.5    68

[153 rows x 5 columns]

In [ ]:
df.to_csv("Manual_Cleaned_Data.csv", index=False)
df

           Date  Ozone  Solar  Wind  Temp
0    01-05-1976   41.0  190.0   7.4    67
1    02-05-1976   36.0  118.0   8.0    72
2    03-05-1976   12.0  149.0  12.6    74
3    04-05-1976   18.0  313.0  11.5    62
4    05-05-1976    NaN    NaN  14.3    56
..          ...    ...    ...   ...   ...
148  26-09-1976   30.0  193.0   6.9    70
149  27-09-1976    NaN  145.0  13.2    77
150  28-09-1976   14.0  191.0  14.3    75
151  29-09-1976   18.0  131.0   8.0    76
152  30-09-1976   20.0  223.0  11.5    68

[153 rows x 5 columns]